const images = {
  calendar: require("../assets/images/calendar.png"),
  lightblueborder: require("../assets/images/Rectangle.png"),
  smallbluebox: require("../assets/images/smallbluebox.png"),
  hidden_eyes: require("../assets/images/hidden_eyes.png"),
  show_eyes: require("../assets/images/show_eyes.png"),
  rightblueborder: require("../assets/images/rightborderblue.png"),
  camera: require("../assets/images/camera.png"),
  userProfile: require("../assets/images/user.png"),
  leftarrow: require("../assets/images/leftarrow.png"),
  loginleftarrow: require("../assets/images/loginleftarrow.png"),
  faceid: require("../assets/images/faceid.png"),
  fingerprint: require("../assets/images/fingerprint.png"),
  backtologin: require("../assets/images/backtologin.png"),
  homeicon: require("../assets/images/homeicon.png"),
  attendanceicon: require("../assets/images/attendanceicon.png"),
  leavesicon: require("../assets/images/leavesicon.png"),
  moreicon: require("../assets/images/moreicon.png"),
  reportsicon: require("../assets/images/reportsicon.png"),
  bell: require("../assets/images/bell.png"),
  squarebox: require("../assets/images/square.png"),
  switch: require("../assets/images/switch.png"),
  redEclipse: require("../assets/images/redEcllipse.png"),
  coffee: require("../assets/images/coffee.png"),
  codeIcon: require('../assets/images/code.png'),
  mobileIcon: require('../assets/images/mobile-alt.png'),
  tagIcon: require('../assets/images/tag.png'),
  oIcon: require('../assets/images/o.png'),
  faceIcon: require('../assets/images/face-idIcon.png'),
  fingerprintIcon: require('../assets/images/fingerprintIcon.png'),
  indexHcl: require('../assets/images/indexHcl.png'),
}
export default images;
